"""Block registry: every block in Minecraft, with properties, families and colours.

See plan.md §4.1 and CONTRACTS.md §6/§7. Loads the mod's `GET /blocks` dump when a bridge is
available, otherwise the bundled `data/blocks_fallback.json` (generated by
`scripts/gen_block_fallback.py`). Families (planks -> stairs/slab/...) are derived by suffix
stripping plus `data/family_overrides.json`. Colours come from the client jar's block textures when a
jar path is given, otherwise `data/block_colors.json`.
"""
from __future__ import annotations

import hashlib
import io
import json
import os
import re
import zipfile
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence, Set, Tuple

from .coretypes import format_state, normalize_id, parse_state, short_id

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
FALLBACK_PATH = os.path.join(DATA_DIR, "blocks_fallback.json")
OVERRIDES_PATH = os.path.join(DATA_DIR, "family_overrides.json")
COLORS_PATH = os.path.join(DATA_DIR, "block_colors.json")
DEFAULT_CACHE_DIR = os.path.join(DATA_DIR, "cache")

RGB = Tuple[int, int, int]
GREY: RGB = (128, 128, 128)

WOODS = ["oak", "spruce", "birch", "jungle", "acacia", "dark_oak", "mangrove", "cherry", "bamboo", "crimson", "warped"]
COLORS = ["white", "orange", "magenta", "light_blue", "yellow", "lime", "pink", "gray", "light_gray", "cyan", "purple", "blue", "brown", "green", "red", "black"]

FORMS = (
    "full", "stairs", "slab", "wall", "fence", "fence_gate", "door", "trapdoor", "button", "pressure_plate",
    "log", "wood", "stripped_log", "stripped_wood", "sign", "leaves", "cracked", "mossy", "chiseled",
    "smooth", "polished", "cut", "bricks", "tiles", "pillar", "powder", "carpet", "pane", "glazed",
)

# suffixes that identify a non-base form (stripped to find the family stem)
_FORM_SUFFIXES = (
    "_planks", "_bricks", "_tiles", "_block", "_stairs", "_slab", "_wall", "_fence_gate", "_fence",
    "_door", "_trapdoor", "_button", "_pressure_plate", "_log", "_wood", "_stem", "_hyphae", "_leaves",
    "_wool", "_carpet", "_concrete_powder", "_concrete", "_stained_glass_pane", "_stained_glass",
    "_glazed_terracotta", "_terracotta", "_pane", "_pillar", "_sign", "_wall_sign", "_hanging_sign",
)
_FORM_PREFIXES = ("stripped_", "cracked_", "mossy_", "chiseled_", "smooth_", "polished_", "cut_", "waxed_")

# substrings that mark a block as NOT a full solid cube (for is_full_block / nearest)
_NON_FULL_MARKERS = (
    "stairs", "slab", "_wall", "fence", "door", "button", "pressure_plate", "sign", "torch", "lantern",
    "chain", "pane", "bars", "carpet", "rail", "wire", "flower", "sapling", "grass", "fern", "bush",
    "vine", "lichen", "roots", "mushroom", "bed", "banner", "candle", "cake", "pot", "skull", "head",
    "ladder", "scaffolding", "lever", "repeater", "comparator", "hook", "egg", "coral", "kelp",
    "seagrass", "pickle", "dripstone", "bamboo", "sugar_cane", "cactus", "lily_pad", "cobweb", "snow",
    "campfire", "bell", "anvil", "cauldron", "hopper", "chest", "brewing", "enchanting", "lectern",
    "grindstone", "stonecutter", "conduit", "end_rod", "amethyst_cluster", "amethyst_bud", "sculk_vein",
    "sensor", "shrieker", "azalea", "petals", "fungus", "sprouts", "propagule", "frogspawn", "tripwire",
    "structure", "barrier", "light", "piston", "bubble", "fire", "portal", "gateway", "dragon_egg",
    "potted", "chorus", "dripleaf", "spore", "farmland", "dirt_path", "powder_snow", "daylight",
    "composter", "shulker", "air", "water", "lava", "beacon", "cocoa", "wheat", "carrots", "potatoes",
    "beetroots", "nether_wart", "berry", "crop", "attached", "tallgrass", "dead_bush", "moving", "jigsaw",
    "command", "spawner", "vault", "heavy_core", "decorated", "flower_pot", "glow_lichen", "hanging",
    "turtle", "sniffer", "frosted", "cave_air", "void_air", "allium", "bluet", "dandelion", "poppy", "tulip",
    "peony", "lilac", "lily", "rose", "pitcher", "melon_stem", "pumpkin_stem", "orchid", "daisy", "torchflower",
    "cornflower", "respawn_anchor", "petals", "sunflower",
)
_FULL_EXCEPTIONS = ("mushroom_block", "mushroom_stem", "bamboo_block", "bamboo_planks", "bamboo_mosaic", "stripped_bamboo_block",
                    "snow_block", "dragon_head_x", "sea_lantern", "redstone_lamp", "bone_block", "coal_block", "hay_block",
                    "coral_block", "light_blue", "light_gray", "chiseled_bookshelf", "bookshelf", "target", "lodestone",
                    "chain_command_block", "sponge", "wet_sponge", "kelp_block", "dried_kelp_block", "amethyst_block",
                    "budding_amethyst", "sculk", "sculk_catalyst", "bee_nest", "beehive", "honey_block", "honeycomb_block")


@dataclass
class BlockDef:
    id: str
    properties: Dict[str, List[str]] = field(default_factory=dict)
    default: Dict[str, str] = field(default_factory=dict)

    @property
    def short(self) -> str:
        return short_id(self.id)


class Registry:
    """The block registry. Build with `Registry.load(...)`."""

    def __init__(self, blocks: Dict[str, BlockDef], source: str = "fallback"):
        self.blocks: Dict[str, BlockDef] = blocks
        self.source = source
        self._overrides: Dict[str, Dict[str, str]] = {}
        self._colors: Dict[str, RGB] = {}
        self._dyes: Dict[str, Dict[str, RGB]] = {}
        self._family_cache: Dict[str, Dict[str, str]] = {}
        self._full_ids: Optional[List[str]] = None
        self._load_overrides()
        self._load_fallback_colors()

    # ------------------------------------------------------------------ loading
    @staticmethod
    def load(bridge: Any = None, client_jar: Optional[str] = None, cache_dir: Optional[str] = None) -> "Registry":
        """Load from the mod (`bridge.blocks()`), else from the bundled fallback dump.

        The mod dump is cached to `cache_dir/blocks_live.json`; texture colours extracted from
        `client_jar` are cached to `cache_dir/colors_<hash>.json`.
        """
        cache_dir = cache_dir or DEFAULT_CACHE_DIR
        raw: Optional[List[dict]] = None
        source = "fallback"
        if bridge is not None:
            try:
                raw = list(bridge.blocks())
                source = "mod"
                if raw:
                    try:
                        os.makedirs(cache_dir, exist_ok=True)
                        with open(os.path.join(cache_dir, "blocks_live.json"), "w") as f:
                            json.dump({"blocks": raw}, f)
                    except OSError:
                        pass
            except Exception:  # noqa: BLE001 - bridge down; fall through to the fallback dump
                raw = None
        if not raw:
            live = os.path.join(cache_dir, "blocks_live.json")
            path = live if os.path.exists(live) else FALLBACK_PATH
            with open(path) as f:
                raw = json.load(f)["blocks"]
            source = "cache" if path == live else "fallback"
        blocks: Dict[str, BlockDef] = {}
        for entry in raw:
            bid = normalize_id(entry["id"])
            props = {k: [str(v) for v in vals] for k, vals in (entry.get("properties") or {}).items()}
            default = entry.get("default")
            if isinstance(default, str):
                _, dprops = parse_state(default)
            elif isinstance(default, dict):
                dprops = {k: str(v) for k, v in default.items()}
            else:
                dprops = {}
            for k, vals in props.items():
                if k not in dprops and vals:
                    dprops[k] = vals[0]
            blocks[bid] = BlockDef(bid, props, dprops)
        reg = Registry(blocks, source)
        if client_jar and os.path.exists(client_jar):
            try:
                reg.load_colors_from_jar(client_jar, cache_dir)
            except Exception:  # noqa: BLE001 - colours are cosmetic; keep the fallback table
                pass
        return reg

    def _load_overrides(self) -> None:
        try:
            with open(OVERRIDES_PATH) as f:
                data = json.load(f)
        except (OSError, ValueError):
            data = {}
        for base, forms in data.items():
            if base.startswith("_"):
                continue
            self._overrides[short_id(normalize_id(base))] = {k: normalize_id(v) for k, v in forms.items()}

    def _load_fallback_colors(self) -> None:
        try:
            with open(COLORS_PATH) as f:
                data = json.load(f)
        except (OSError, ValueError):
            data = {}
        self._dyes = {k: {c: tuple(v) for c, v in d.items()} for k, d in data.get("_dyes", {}).items()}
        for k, v in data.items():
            if k.startswith("_"):
                continue
            self._colors[k] = (int(v[0]), int(v[1]), int(v[2]))

    def load_colors_from_jar(self, jar_path: str, cache_dir: Optional[str] = None) -> int:
        """Average the RGB of every `assets/minecraft/textures/block/*.png` in the client jar.

        Grass/logs/etc. prefer their `_top` texture. Returns the number of colours loaded.
        """
        cache_dir = cache_dir or DEFAULT_CACHE_DIR
        h = hashlib.sha1((jar_path + str(os.path.getsize(jar_path))).encode()).hexdigest()[:12]
        cache_path = os.path.join(cache_dir, f"colors_{h}.json")
        if os.path.exists(cache_path):
            with open(cache_path) as f:
                data = json.load(f)
            self._colors.update({k: tuple(v) for k, v in data.items()})
            return len(data)
        from PIL import Image  # local import: PIL is only needed here

        textures: Dict[str, RGB] = {}
        with zipfile.ZipFile(jar_path) as z:
            for name in z.namelist():
                if not name.startswith("assets/minecraft/textures/block/") or not name.endswith(".png"):
                    continue
                key = name.rsplit("/", 1)[1][:-4]
                try:
                    img = Image.open(io.BytesIO(z.read(name))).convert("RGBA")
                except Exception:  # noqa: BLE001
                    continue
                px = [p for p in img.getdata() if p[3] > 0]
                if not px:
                    continue
                n = len(px)
                textures[key] = (sum(p[0] for p in px) // n, sum(p[1] for p in px) // n, sum(p[2] for p in px) // n)
        found: Dict[str, RGB] = {}
        for bid in self.blocks:
            s = short_id(bid)
            for cand in (s + "_top", s, s + "_side", s + "_front", s.replace("_block", ""), s + "_0", s + "_bottom"):
                if cand in textures:
                    found[s] = textures[cand]
                    break
        # grass_block texture is a greyscale colormap mask; use the biome-tinted average
        if "grass_block" in found and sum(found["grass_block"]) > 500:
            found["grass_block"] = (127, 178, 56)
        self._colors.update(found)
        try:
            os.makedirs(cache_dir, exist_ok=True)
            with open(cache_path, "w") as f:
                json.dump(found, f)
        except OSError:
            pass
        return len(found)

    # ------------------------------------------------------------------ basics
    def has(self, block_id: str) -> bool:
        """True if the block id (with or without `minecraft:`) exists."""
        return normalize_id(block_id.split("[")[0]) in self.blocks

    def get(self, block_id: str) -> Optional[BlockDef]:
        return self.blocks.get(normalize_id(block_id.split("[")[0]))

    def ids(self) -> List[str]:
        return list(self.blocks)

    def __len__(self) -> int:
        return len(self.blocks)

    def __contains__(self, block_id: str) -> bool:
        return self.has(block_id)

    def validate_state(self, state: str, fill_defaults: bool = True) -> Tuple[bool, str]:
        """Validate `minecraft:id[prop=val,...]`.

        Returns (True, normalised state) or (False, error message). With `fill_defaults` the
        normalised state lists every property (game defaults for the ones not given); otherwise
        only the given properties are kept (sorted). Unknown properties/values are errors.
        """
        try:
            bid, props = parse_state(state)
        except Exception as e:  # noqa: BLE001
            return False, f"cannot parse block state {state!r}: {e}"
        bdef = self.blocks.get(bid)
        if bdef is None:
            sugg = self.search(short_id(bid), limit=3)
            hint = f"; did you mean {', '.join(short_id(s) for s in sugg)}?" if sugg else ""
            return False, f"unknown block {bid}{hint}"
        out: Dict[str, str] = {}
        for k, v in props.items():
            if k not in bdef.properties:
                return False, f"{bid} has no property {k!r}; properties: {', '.join(bdef.properties) or '(none)'}"
            if v not in bdef.properties[k]:
                return False, f"{bid}[{k}={v}] is invalid; allowed: {', '.join(bdef.properties[k])}"
            out[k] = v
        if fill_defaults:
            for k, dv in bdef.default.items():
                out.setdefault(k, dv)
        return True, format_state(bid, out)

    def normalize(self, state: str, fill_defaults: bool = False) -> str:
        """Like validate_state but raises ValueError on invalid input."""
        ok, res = self.validate_state(state, fill_defaults=fill_defaults)
        if not ok:
            raise ValueError(res)
        return res

    def default_state(self, block_id: str) -> str:
        b = self.get(block_id)
        if b is None:
            raise ValueError(f"unknown block {block_id}")
        return format_state(b.id, b.default)

    # ------------------------------------------------------------------ families
    def family(self, base_id: str) -> Dict[str, str]:
        """Map form -> block id for the family of `base_id` (e.g. planks -> stairs/slab/fence/...).

        Always contains `full` (the base itself, if it exists). Forms whose block does not exist are
        omitted, so `"stairs" in registry.family(x)` is the right existence test.
        """
        base = short_id(normalize_id(base_id.split("[")[0]))
        if base in self._family_cache:
            return dict(self._family_cache[base])
        fam: Dict[str, str] = {}
        if self.has(base):
            fam["full"] = normalize_id(base)
        stems = self._candidate_stems(base)
        patterns = {
            "stairs": "{s}_stairs", "slab": "{s}_slab", "wall": "{s}_wall", "fence": "{s}_fence",
            "fence_gate": "{s}_fence_gate", "door": "{s}_door", "trapdoor": "{s}_trapdoor", "button": "{s}_button",
            "pressure_plate": "{s}_pressure_plate", "log": "{s}_log", "wood": "{s}_wood",
            "stripped_log": "stripped_{s}_log", "stripped_wood": "stripped_{s}_wood", "sign": "{s}_sign",
            "leaves": "{s}_leaves", "bricks": "{s}_bricks", "tiles": "{s}_tiles", "pillar": "{s}_pillar",
            "carpet": "{s}_carpet", "glazed": "{s}_glazed_terracotta",
        }
        for form, pat in patterns.items():
            for s in stems:
                cand = pat.format(s=s)
                if cand != base and self.has(cand):
                    fam[form] = normalize_id(cand)
                    break
        for form, pat in (("cracked", "cracked_{b}"), ("mossy", "mossy_{b}"), ("chiseled", "chiseled_{b}"),
                          ("smooth", "smooth_{b}"), ("polished", "polished_{b}"), ("cut", "cut_{b}"),
                          ("powder", "{b}_powder"), ("pane", "{b}_pane")):
            cand = pat.format(b=base)
            if self.has(cand):
                fam.setdefault(form, normalize_id(cand))
        if "powder" not in fam and base.endswith("_concrete_powder"):
            fam["full"] = normalize_id(base[: -len("_powder")]) if self.has(base[: -len("_powder")]) else fam.get("full", "")
        # planks-derived forms for logs (oak_log -> oak_stairs via stem "oak")
        for k, v in self._overrides.get(base, {}).items():
            if self.has(v):
                fam[k] = v
        fam = {k: v for k, v in fam.items() if v}
        self._family_cache[base] = fam
        return dict(fam)

    def _candidate_stems(self, base: str) -> List[str]:
        stems = [base]
        b = base
        # singular forms first (stone_bricks -> stone_brick), then suffix stripping
        for suf, rep in (("_bricks", "_brick"), ("_tiles", "_tile"), ("_planks", ""), ("_block", ""), ("_wool", ""),
                         ("_concrete_powder", "_concrete"), ("_stained_glass_pane", "_stained_glass"),
                         ("_glazed_terracotta", "_terracotta"), ("_terracotta", ""), ("_log", ""), ("_wood", ""),
                         ("_stem", ""), ("_hyphae", ""), ("_leaves", ""), ("_stairs", ""), ("_slab", ""), ("_wall", ""),
                         ("_fence_gate", ""), ("_fence", ""), ("_door", ""), ("_trapdoor", ""), ("_button", ""),
                         ("_pressure_plate", ""), ("_pillar", ""), ("_carpet", ""), ("_sign", "")):
            if b.endswith(suf):
                stem = b[: -len(suf)] + rep
                if stem and stem not in stems:
                    stems.append(stem)
                if suf == "_bricks" and base == "bricks":
                    stems.append("brick")
        if base == "bricks":
            stems.append("brick")
        for pre in _FORM_PREFIXES:
            if base.startswith(pre):
                rest = base[len(pre):]
                if rest and rest not in stems:
                    stems.append(rest)
                    for s in list(self._candidate_stems(rest)):
                        if s not in stems:
                            stems.append(s)
        return stems

    def families_report(self) -> List[str]:
        """Full solid blocks (building materials) whose family has neither stairs nor slab."""
        out = []
        for bid in self.blocks:
            s = short_id(bid)
            if not self.is_full_block(s):
                continue
            if any(m in s for m in ("ore", "_wool", "_concrete", "_terracotta", "glass", "leaves", "coral", "froglight", "infested", "sculk", "spawner", "command", "structure", "jigsaw")):
                continue
            fam = self.family(s)
            if "stairs" not in fam and "slab" not in fam:
                out.append(s)
        return sorted(out)

    # ------------------------------------------------------------------ colours
    def color(self, id_or_state: str) -> RGB:
        """Average RGB for a block id or state string (falls back through family and dye tables)."""
        s = short_id(normalize_id(id_or_state.split("[")[0]))
        c = self._colors.get(s)
        if c:
            return c
        # dye colours: <color>_<form>
        for col in COLORS:
            if s.startswith(col + "_"):
                form = s[len(col) + 1:]
                for key in (form, form.replace("stained_glass_pane", "stained_glass"), "wool"):
                    d = self._dyes.get(key)
                    if d and col in d:
                        return d[col]
        # form suffix stripping: oak_stairs -> oak_planks / oak
        for suf in _FORM_SUFFIXES:
            if s.endswith(suf) and s != suf:
                stem = s[: -len(suf)]
                for cand in (stem, stem + "_planks", stem + "_block", stem + "s", stem + "_bricks"):
                    if cand in self._colors:
                        return self._colors[cand]
        for pre in _FORM_PREFIXES:
            if s.startswith(pre):
                c2 = self._colors.get(s[len(pre):])
                if c2:
                    return self._tint(c2, pre)
        if s.endswith("_stairs") or s.endswith("_slab") or s.endswith("_wall"):
            stem = s.rsplit("_", 1)[0]
            fam_full = None
            for cand in (stem + "s", stem, stem + "_planks", stem + "_block"):
                if cand in self._colors:
                    fam_full = cand
                    break
            if fam_full:
                return self._colors[fam_full]
        for wood in WOODS:
            if s.startswith(wood + "_") or s.startswith("stripped_" + wood):
                return self._colors.get(wood + "_planks", GREY)
        return GREY

    @staticmethod
    def _tint(c: RGB, pre: str) -> RGB:
        if pre == "mossy_":
            return (int(c[0] * 0.85), int(c[1] * 0.95), int(c[2] * 0.8))
        if pre == "cracked_":
            return (int(c[0] * 0.95), int(c[1] * 0.95), int(c[2] * 0.95))
        if pre == "stripped_":
            return (min(255, int(c[0] * 1.3)), min(255, int(c[1] * 1.3)), min(255, int(c[2] * 1.2)))
        return c

    # ------------------------------------------------------------------ search / categories
    def search(self, query: str, limit: int = 20) -> List[str]:
        """Find block ids matching every word of `query` (substring match, then fuzzy on typos)."""
        words = [w for w in re.split(r"[\s,]+", query.strip().lower().replace("minecraft:", "")) if w]
        if not words:
            return []
        scored: List[Tuple[float, str]] = []
        for bid in self.blocks:
            s = short_id(bid)
            score = 0.0
            ok = True
            for w in words:
                if w in s:
                    score += 2.0 if s.startswith(w) or f"_{w}" in s else 1.0
                elif _fuzzy_in(w, s):
                    score += 0.5
                else:
                    ok = False
                    break
            if ok:
                scored.append((score - len(s) / 100.0, bid))
        scored.sort(key=lambda t: (-t[0], t[1]))
        return [b for _, b in scored[:limit]]

    def categories(self, block_id: str) -> Set[str]:
        """Coarse tags for a block id: wood, stone, wool, concrete, terracotta, glass, nature, ore, metal, light, prop, functional, redstone, full, color:<name>."""
        s = short_id(normalize_id(block_id.split("[")[0]))
        cats: Set[str] = set()
        for col in COLORS:
            if s.startswith(col + "_"):
                cats.add("color:" + col)
        if any(s.startswith(w + "_") or s.startswith("stripped_" + w) for w in WOODS) or s in ("bamboo_block", "bamboo_mosaic", "stripped_bamboo_block"):
            cats.add("wood")
        if "wool" in s:
            cats.add("wool")
        if "concrete" in s:
            cats.add("concrete")
        if "terracotta" in s:
            cats.add("terracotta")
        if "glass" in s:
            cats.add("glass")
        if any(k in s for k in ("stone", "brick", "deepslate", "tuff", "andesite", "diorite", "granite", "basalt", "blackstone", "prismarine", "purpur", "quartz", "obsidian", "netherrack", "calcite", "dripstone", "mud", "sandstone")) and "glass" not in s:
            cats.add("stone")
        if "_ore" in s or s.startswith("raw_") or s == "ancient_debris":
            cats.add("ore")
        if any(s == m for m in ("iron_block", "gold_block", "copper_block", "netherite_block", "diamond_block", "emerald_block", "lapis_block", "redstone_block", "coal_block")) or "copper" in s:
            cats.add("metal")
        if any(k in s for k in ("lantern", "torch", "glowstone", "shroomlight", "sea_lantern", "end_rod", "campfire", "froglight", "redstone_lamp", "candle", "jack_o_lantern", "copper_bulb", "light")):
            cats.add("light")
        if any(k in s for k in ("dirt", "grass", "sand", "gravel", "leaves", "flower", "sapling", "moss", "snow", "ice", "water", "lava", "clay", "vine", "fern", "bush", "mushroom", "kelp", "coral", "cactus", "bamboo", "hay", "pumpkin", "melon", "log", "wood", "podzol", "mycelium", "mud", "roots", "azalea", "petals", "lily", "sugar_cane", "dead_bush", "lichen", "sculk", "amethyst")):
            cats.add("nature")
        if any(k in s for k in ("redstone", "repeater", "comparator", "lever", "button", "pressure_plate", "observer", "piston", "dispenser", "dropper", "hopper", "tnt", "daylight", "target", "tripwire", "rail", "note_block")):
            cats.add("redstone")
        if any(k in s for k in ("table", "furnace", "smoker", "chest", "barrel", "anvil", "cauldron", "composter", "lectern", "loom", "grindstone", "stonecutter", "bell", "beacon", "conduit", "brewing", "jukebox", "bookshelf", "bed", "campfire", "ladder", "scaffolding", "door", "trapdoor", "fence_gate")):
            cats.add("functional")
        if any(k in s for k in ("banner", "flower_pot", "potted", "head", "skull", "candle", "sign", "chain", "bars", "pane", "carpet", "lantern", "torch", "end_rod", "cake", "decorated_pot", "item_frame", "bell", "cobweb")):
            cats.add("prop")
        if self.is_full_block(s):
            cats.add("full")
        return cats

    def is_full_block(self, block_id: str) -> bool:
        """Heuristic: True for opaque/transparent full cubes usable as building material."""
        s = short_id(normalize_id(block_id.split("[")[0]))
        if s in ("air", "cave_air", "void_air"):
            return False
        for exc in _FULL_EXCEPTIONS:
            if s.endswith(exc) or s == exc:
                if not any(m in s for m in ("potted", "stairs", "slab")):
                    return True
        return not any(m in s for m in _NON_FULL_MARKERS)

    def full_block_ids(self) -> List[str]:
        if self._full_ids is None:
            self._full_ids = [b for b in self.blocks if self.is_full_block(b)]
        return list(self._full_ids)

    def nearest(self, rgb: Sequence[float], category: Optional[str] = None) -> str:
        """The full block whose average colour is closest to `rgb`.

        `category` restricts the search: full (default), wool, concrete, terracotta, glass, wood,
        stone, any. Distance is weighted RGB (perceptual-ish).
        """
        cat = (category or "full").lower()
        if cat in ("any", "all", "full", None):
            cands = self.full_block_ids() if cat != "any" else list(self.blocks)
        else:
            cands = [b for b in self.blocks if cat in self.categories(b) and (self.is_full_block(b) or cat == "glass")]
            if not cands:
                cands = self.full_block_ids()
        r0, g0, b0 = float(rgb[0]), float(rgb[1]), float(rgb[2])
        best, best_d = cands[0], float("inf")
        for bid in cands:
            s = short_id(bid)
            if any(k in s for k in ("_ore", "infested", "command", "structure", "jigsaw", "spawner", "barrier", "bedrock", "air")):
                continue
            c = self.color(bid)
            d = 0.3 * (c[0] - r0) ** 2 + 0.59 * (c[1] - g0) ** 2 + 0.11 * (c[2] - b0) ** 2
            if d < best_d:
                best, best_d = bid, d
        return best

    # ------------------------------------------------------------------ catalog
    def catalog_text(self) -> str:
        """Compressed materials catalog for the system prompt (~2.5k tokens). Counts are live."""
        n = len(self.blocks)
        woods = [w for w in WOODS if self.has(f"{w}_planks")]
        stone_bases = [
            "stone", "cobblestone", "mossy_cobblestone", "stone_bricks", "mossy_stone_bricks", "smooth_stone", "andesite",
            "polished_andesite", "diorite", "polished_diorite", "granite", "polished_granite", "cobbled_deepslate",
            "polished_deepslate", "deepslate_bricks", "deepslate_tiles", "tuff", "polished_tuff", "tuff_bricks",
            "blackstone", "polished_blackstone", "polished_blackstone_bricks", "sandstone", "smooth_sandstone",
            "red_sandstone", "smooth_red_sandstone", "bricks", "mud_bricks", "nether_bricks", "red_nether_bricks",
            "end_stone_bricks", "prismarine", "prismarine_bricks", "dark_prismarine", "purpur_block", "quartz_block",
            "smooth_quartz", "cut_copper", "exposed_cut_copper", "weathered_cut_copper", "oxidized_cut_copper",
        ]
        rows = []
        for b in stone_bases:
            if not self.has(b):
                continue
            fam = self.family(b)
            forms = [f for f in ("stairs", "slab", "wall") if f in fam]
            rows.append(f"{b}({'/'.join(forms) if forms else 'full only'})")
        colors = ", ".join(COLORS)
        lines = [
            f"MATERIALS CATALOG ({n} vanilla blocks; ids are minecraft:<name>; use search_blocks for anything not listed)",
            "",
            f"WOOD ({len(woods)} types: {', '.join(woods)}) — each has: <wood>_planks, <wood>_log (axis=x|y|z), <wood>_wood, stripped_<wood>_log/wood, <wood>_stairs, <wood>_slab, <wood>_fence, <wood>_fence_gate, <wood>_door, <wood>_trapdoor, <wood>_button, <wood>_pressure_plate, <wood>_sign, <wood>_hanging_sign, <wood>_leaves (not bamboo/crimson/warped). crimson/warped use _stem/_hyphae instead of _log/_wood; bamboo has bamboo_block and bamboo_mosaic(stairs/slab).",
            "  Looks: oak=warm tan, spruce=dark brown, birch=pale cream, jungle=reddish, acacia=orange, dark_oak=very dark, mangrove=red-brown, cherry=pink-white, bamboo=yellow, crimson=magenta, warped=teal.",
            "",
            "STONE (full block → available forms): " + ", ".join(rows),
            "  Variants: cracked_/mossy_/chiseled_ stone_bricks, deepslate_bricks/tiles; chiseled_deepslate, chiseled_tuff, chiseled_polished_blackstone, chiseled_sandstone, chiseled_quartz_block, quartz_bricks, quartz_pillar, purpur_pillar, cut_sandstone, basalt/smooth_basalt/polished_basalt (axis), calcite, dripstone_block, obsidian, crying_obsidian, netherrack, end_stone, packed_mud, mud.",
            "  Looks: stone_bricks=classic grey castle; cobblestone=rough grey; andesite=mid grey; diorite=white speckled; granite=pink-brown; deepslate=dark grey-blue; tuff=grey-green; blackstone=near black; sandstone=pale yellow; red_sandstone=orange; bricks=red clay; mud_bricks=tan; nether_bricks=dark red; prismarine=teal; purpur=lavender; quartz=bright white; copper=orange→green as it oxidises.",
            "",
            f"COLOURS (16: {colors}) × forms: <c>_wool, <c>_carpet, <c>_concrete (flat, saturated), <c>_concrete_powder, <c>_terracotta (muted earth tones), <c>_glazed_terracotta (patterned, facing), <c>_stained_glass, <c>_stained_glass_pane, <c>_bed, <c>_banner (rotation=0..15) / <c>_wall_banner (facing), <c>_candle, <c>_shulker_box. Plain: terracotta, glass, glass_pane, tinted_glass.",
            "",
            "METALS/ORES: iron_block, gold_block, copper_block (+exposed_/weathered_/oxidized_ and waxed_ variants; cut_copper stairs/slab, copper_grate, copper_bulb, copper_door/trapdoor, chiseled_copper), netherite_block, diamond_block, emerald_block, lapis_block, redstone_block, coal_block, raw_iron/copper/gold_block, amethyst_block, iron_bars (pane), chain (axis), iron_door, iron_trapdoor, anvil, cauldron, bell, lightning_rod. Ores: coal/iron/copper/gold/redstone/emerald/lapis/diamond_ore (+deepslate_ variants), nether_gold_ore, nether_quartz_ore, ancient_debris.",
            "",
            "NATURE: grass_block, dirt, coarse_dirt, rooted_dirt, podzol, mycelium, dirt_path, farmland, mud, clay, sand, red_sand, gravel, moss_block, moss_carpet, snow_block, snow (layers=1..8), ice, packed_ice, blue_ice, water, lava, hay_block (axis), bone_block, pumpkin, carved_pumpkin (facing), melon, sponge, honey_block, slime_block. Plants: short_grass, fern, tall_grass, large_fern, dead_bush, dandelion, poppy, blue_orchid, allium, azure_bluet, red/orange/white/pink_tulip, oxeye_daisy, cornflower, lily_of_the_valley, wither_rose, torchflower, sunflower/lilac/rose_bush/peony (2 tall), pink_petals, azalea, flowering_azalea, brown/red_mushroom (+_block), vine, glow_lichen, hanging_roots, lily_pad, sugar_cane, cactus, bamboo, kelp, seagrass, sea_pickle, coral (tube/brain/bubble/fire/horn *_coral_block/_coral/_coral_fan), spore_blossom, big/small_dripleaf, cave_vines, weeping_vines, twisting_vines, crimson/warped_fungus/roots/nylium, nether_wart_block, warped_wart_block, shroomlight, sculk, amethyst_cluster, pointed_dripstone.",
            "",
            "LIGHTING: lantern / soul_lantern (hanging=true|false), torch, wall_torch (facing), soul_torch, soul_wall_torch, glowstone, sea_lantern, shroomlight, end_rod (facing=up|down|north..), campfire / soul_campfire (lit, facing), jack_o_lantern (facing), redstone_lamp (lit=true needs power), ochre/verdant/pearlescent_froglight (axis), candle / <c>_candle (candles=1..4, lit), copper_bulb (lit), light (level=0..15, invisible).",
            "",
            "PROPS & FUNCTIONAL: chest / trapped_chest (facing), ender_chest, barrel, crafting_table, furnace / blast_furnace / smoker (facing, lit), smithing_table, fletching_table, cartography_table, loom, stonecutter, grindstone (face, facing), lectern (facing), enchanting_table, brewing_stand, anvil (facing), composter, bookshelf, chiseled_bookshelf (facing), jukebox, note_block, bee_nest / beehive (facing), beacon, conduit, lodestone, flower_pot, potted_<plant>, decorated_pot (facing), cake, <c>_bed (facing, part=head|foot), ladder (facing), scaffolding, cobweb, <wood>_door / iron_door / copper_door (facing, half=lower|upper, hinge, open), <wood>_trapdoor (facing, half, open), <wood>_fence_gate (facing), heads: skeleton_skull, wither_skeleton_skull, zombie_head, player_head, creeper_head, dragon_head, piglin_head (rotation) and *_wall_skull/_wall_head (facing).",
            "",
            "REDSTONE/RAILS: redstone_wire, redstone_torch, repeater, comparator, lever, stone_button, <wood>_button, observer, piston, sticky_piston, dispenser, dropper, hopper, tnt, daylight_detector, target, tripwire_hook, rail, powered_rail, detector_rail, activator_rail, note_block.",
            "",
            "STATE RULES: stairs[facing=north|south|east|west,half=bottom|top] (facing = direction of the full/high side; never set shape), slab[type=bottom|top|double], logs/pillars[axis], walls/fences/panes/iron_bars connect automatically (never set north/east/...). Doors need both halves (the resolver places the upper half). Materials reference the FULL block; stairs/slab/wall forms are derived automatically when the material's fit allows it.",
        ]
        return "\n".join(lines)


def _fuzzy_in(word: str, target: str) -> bool:
    """Cheap typo tolerance: word matches if it appears with one character wrong/missing."""
    if len(word) < 4:
        return False
    for i in range(len(word)):
        if word[:i] + word[i + 1:] in target:
            return True
    for i in range(1, len(word)):
        if word[:i] in target and word[i:] in target:
            return True
    return False


_DEFAULT: Optional[Registry] = None


def default_registry() -> Registry:
    """Process-wide fallback registry (no game required). Cached."""
    global _DEFAULT
    if _DEFAULT is None:
        _DEFAULT = Registry.load()
    return _DEFAULT
