"""Schematic export (.litematic via litemapy) and survival materials lists (plan.md §9)."""
from __future__ import annotations

import os
from collections import Counter
from typing import List, Tuple

from .coretypes import BlockMap, parse_state, short_id


def export_litematic(block_map: BlockMap, name: str, path: str, author: str = "minecraft-copilot") -> str:
    """Write `block_map` (world coords) as a single-region .litematic at `path` and return the path.

    The region origin is the block map's minimum corner, so the schematic pastes relative to it.
    """
    from litemapy import BlockState, Region

    if not block_map:
        raise ValueError("block map is empty; nothing to export")
    xs = [p[0] for p in block_map]
    ys = [p[1] for p in block_map]
    zs = [p[2] for p in block_map]
    x0, y0, z0 = min(xs), min(ys), min(zs)
    w, h, l = max(xs) - x0 + 1, max(ys) - y0 + 1, max(zs) - z0 + 1
    region = Region(0, 0, 0, w, h, l)
    cache: dict = {}
    for (x, y, z), state in block_map.items():
        bs = cache.get(state)
        if bs is None:
            bid, props = parse_state(state)
            bs = BlockState(bid, **props)
            cache[state] = bs
        region[x - x0, y - y0, z - z0] = bs
    schem = region.as_schematic(name=name, author=author, description="Generated by Minecraft Copilot")
    if not path.endswith(".litematic"):
        path += ".litematic"
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    schem.save(path)
    return path


def materials_list(block_map: BlockMap) -> List[Tuple[str, int]]:
    """[(block_id, count)] sorted by count desc, ignoring block-state properties."""
    c: Counter = Counter()
    for state in block_map.values():
        bid, _ = parse_state(state)
        if bid != "minecraft:air":
            c[bid] += 1
    return sorted(c.items(), key=lambda t: (-t[1], t[0]))


def stacks_text(n: int) -> str:
    """Survival-friendly count: `3 stacks + 12` (64 per stack); `12` under a stack; shulkers at ≥ 27 stacks."""
    stacks, rest = divmod(n, 64)
    if stacks == 0:
        return str(rest)
    text = f"{stacks} stack{'s' if stacks != 1 else ''}" + (f" + {rest}" if rest else "")
    if stacks >= 27:
        boxes, box_rest = divmod(stacks, 27)
        text += f" = {boxes} shulker{'s' if boxes != 1 else ''}" + (f" + {box_rest} stack{'s' if box_rest != 1 else ''}" if box_rest else "")
    return text


def materials_list_text(block_map: BlockMap, limit: int = 40) -> str:
    """Human-readable materials list for survival players: stacks (64) and shulker boxes (27 stacks)."""
    rows = materials_list(block_map)
    if not rows:
        return "no blocks"
    total = sum(n for _, n in rows)
    total_stacks = -(-total // 64)
    header = f"{total} blocks ({total_stacks} stacks"
    if total_stacks >= 27:
        header += f", {-(-total_stacks // 27)} shulker boxes"
    header += f"), {len(rows)} block types:"
    lines = [header]
    width = min(32, max(len(short_id(bid)) for bid, _ in rows[:limit]))
    for bid, n in rows[:limit]:
        lines.append(f"  {short_id(bid):<{width}} {n:>6}  ({stacks_text(n)})")
    if len(rows) > limit:
        lines.append(f"  ... {len(rows) - limit} more types ({sum(n for _, n in rows[limit:])} blocks)")
    return "\n".join(lines)
