"""Schematic export (.litematic via litemapy) and survival materials lists (plan.md §9)."""
from __future__ import annotations

import os
from collections import Counter
from typing import List, Tuple

from .coretypes import BlockMap, parse_state, short_id


def export_litematic(block_map: BlockMap, name: str, path: str, author: str = "minecraft-copilot") -> str:
    """Write `block_map` (world coords) as a single-region .litematic at `path` and return the path.

    The region origin is the block map's minimum corner, so the schematic pastes relative to it.
    """
    from litemapy import BlockState, Region

    if not block_map:
        raise ValueError("block map is empty; nothing to export")
    xs = [p[0] for p in block_map]
    ys = [p[1] for p in block_map]
    zs = [p[2] for p in block_map]
    x0, y0, z0 = min(xs), min(ys), min(zs)
    w, h, l = max(xs) - x0 + 1, max(ys) - y0 + 1, max(zs) - z0 + 1
    region = Region(0, 0, 0, w, h, l)
    cache = {}
    for (x, y, z), state in block_map.items():
        bs = cache.get(state)
        if bs is None:
            bid, props = parse_state(state)
            bs = BlockState(bid, **props)
            cache[state] = bs
        region[x - x0, y - y0, z - z0] = bs
    schem = region.as_schematic(name=name, author=author, description="Generated by Minecraft Copilot")
    if not path.endswith(".litematic"):
        path += ".litematic"
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    schem.save(path)
    return path


def materials_list(block_map: BlockMap) -> List[Tuple[str, int]]:
    """[(block_id, count)] sorted by count desc, ignoring block-state properties."""
    c: Counter = Counter()
    for state in block_map.values():
        bid, _ = parse_state(state)
        if bid != "minecraft:air":
            c[bid] += 1
    return sorted(c.items(), key=lambda t: (-t[1], t[0]))


def materials_list_text(block_map: BlockMap, limit: int = 40) -> str:
    """Human-readable materials list with stacks (64) and shulker boxes (27 stacks)."""
    rows = materials_list(block_map)
    if not rows:
        return "no blocks"
    total = sum(n for _, n in rows)
    lines = [f"{total} blocks, {len(rows)} block types:"]
    for bid, n in rows[:limit]:
        stacks = n / 64.0
        extra = f" ({stacks:.1f} stacks" + (f", {stacks / 27:.1f} shulkers)" if stacks >= 27 else ")")
        lines.append(f"  {short_id(bid):<32} {n:>7}{extra}")
    if len(rows) > limit:
        lines.append(f"  ... {len(rows) - limit} more types")
    return "\n".join(lines)
